spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/payment
    username: fitcore
    password: fitcorepass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: fitcore-rabbitmq
    port: 5672
    username: admin
    password: admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: oficial.fitcore@gmail.com
    password: jnci tygt rroj xavc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        from: "FitCore oficial.fitcore@gmail.com"

pagarme:
  api-key: "sk_test_18d0d43fa4374be69c1774196abebca0"
  base-url: "https://api.pagar.me/core/v5"

server:
  port: 8080

minio:
  url: http://localhost:9000/
  access-key: minio
  secret-key: minio123
  bucket: fitcore

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.amqp.rabbit: DEBUG
    org.springframework.amqp.rabbit.core: DEBUG
    org.springframework.amqp.rabbit.connection: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG
    org.apache.http.wire: DEBUG